spring.application.name=catalogo

# Servidor
server.port=8080

# Datasource H2 en memoria
spring.datasource.url=jdbc:h2:mem:tiendaya;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Consola web de H2, util para inspeccionar los datos en el navegador
# Disponible en /h2-console (JDBC URL: jdbc:h2:mem:tiendaya)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Permite que data.sql se ejecute DESPUES de que Hibernate cree el esquema
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Mostrar mensaje de error de Spring MVC en vez de "Whitelabel Error Page" generico
server.error.include-message=always
