spring.application.name=catalogo

# Servidor
server.port=8080

# Datasource Oracle
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=TASKFLOW_USER
spring.datasource.password=TaskFlow123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Permite que data.sql se ejecute DESPUES de que Hibernate cree el esquema
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Mostrar mensaje de error de Spring MVC en vez de "Whitelabel Error Page" generico
server.error.include-message=always
